### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by frankyxcs** [paul-blundell/Order-Some-Food#1]
Hi Paul 
your script looks very nice but there are some files missing. could you upload 
the missing  _htaccess and the index.php for the root folder please to geht the script to work

thanx frank

**Comment by paul-blundell** [comment]
Hi,
You should be able to find these in the `public` folder. Point your web server to the public folder, instead of the root folder.
Let me know if there's still an issue here.
Thanks.
